---
abstract: 'Dist::Zilla with Changes check'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-CheckChangeLog
requires:
  Dist::Zilla: '1.007'
  Moose::Autobox: '0'
resources:
  repository: git://github.com/fayland/dist-zilla-plugin-checkchangelog.git
version: '0.02'
